# Generated by Django 5.1.1 on 2024-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
